#!/bin/bash

# =================================================================
# Script 5: Open Source Manifesto Generator
# Author: ADARSH PATEL
# Registration Number: 24BCY10312
# Course: Open Source Software (OSS)
# =================================================================

# Clear the screen to give a professional starting point for the audit demo
clear

echo "==============================================================="
echo "       PERSONAL OPEN SOURCE MANIFESTO GENERATOR                "
echo "==============================================================="
echo "Welcome, $USER. Let's document your stance on FOSS philosophy."
echo ""

# --- Interactive Input ---
# These questions are designed to show personal engagement with the course
read -p "1. Which OSS tool has helped you the most in your studies? " FAV_TOOL
read -p "2. Define 'Software Freedom' in your own words: " FREEDOM_DEF
read -p "3. What is one thing you'd like to contribute to a repo? " CONTRIB_IDEA

# Metadata for the file
GEN_DATE=$(date '+%A, %d %B %Y')
FILENAME="manifesto_$(whoami)_24BCY10312.txt"

echo ""
echo "[SYSTEM] Processing your reflections..."
sleep 1.5 # Adding a small delay for a more 'human' interactive feel

# --- File Generation ---
# Using '>' to overwrite/create and '>>' to append
echo "---------------------------------------------------------------" > $FILENAME
echo "             MY OPEN SOURCE MANIFESTO                          " >> $FILENAME
echo "---------------------------------------------------------------" >> $FILENAME
echo "Generated by: ADARSH PATEL (24BCY10312)" >> $FILENAME
echo "Date: $GEN_DATE" >> $FILENAME
echo "" >> $FILENAME
echo "I believe that tools like $FAV_TOOL are essential because they" >> $FILENAME
echo "break down the barriers to high-quality education." >> $FILENAME
echo "" >> $FILENAME
echo "To me, freedom in software means: $FREEDOM_DEF" >> $FILENAME
echo "" >> $FILENAME
echo "My Goal: I want to give back to the community by working on" >> $FILENAME
echo "$CONTRIB_IDEA, ensuring that the next generation of students" >> $FILENAME
echo "has even better tools than I did." >> $FILENAME
echo "---------------------------------------------------------------" >> $FILENAME

# --- Final Output ---
echo "[SUCCESS] Your manifesto has been compiled into: $FILENAME"
echo "DISPLAYING GENERATED CONTENT:"
echo ""
cat $FILENAME
echo ""
echo "==============================================================="
